### ISSUE TITLE
convert to geotype ?

### ISSUE THREAD

**Issue by Farkal** [tmontaigu/shapefile-rs#1]
Hey, 

Thanks for the great parsing but i would like to convert your object to geotype. 

I try with try_into but doesn't work. Have you any idea on how to do this ?

**Comment by tmontaigu** [comment]
At the moment since the `From`and `TryFrom` for geo_types are not implementented, you cannot use them  (with things like try into) to convert the Shapes read to the ones in the geo_types crate.
 You have to convert them manually.

I'll look into adding this feature

**Comment by tmontaigu** [comment]
I implemented Some `From` and `TryFrom` traits to converts to geo-types data structs  hoping they can be useful

**Comment by rfilmyer** [comment]
Sorry, the documentation isn't very clear here - if I have a `shapefile::Polygon` that I want to convert to a `geo_types::MultiPolygon<f64>`, how do I do it?

I tried just doing `source = geo_types::MultiPolygon::from(source)` and got the following error:

```
error[E0277]: the trait bound `geo_types::polygon::Polygon<_>: std::convert::From<shapefile::record::polygon::GenericPolygon<T>>` is not satisfied
  --> src/main.rs:49:14
   |
49 |     source = geo_types::MultiPolygon::from(source)
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<shapefile::record::polygon::GenericPolygon<T>>` is not implemented for `geo_types::polygon::Polygon<_>`
   |
   = help: the following implementations were found:
             <geo_types::polygon::Polygon<T> as std::convert::From<geo_types::rect::Rect<T>>>
             <geo_types::polygon::Polygon<T> as std::convert::From<geo_types::triangle::Triangle<T>>>
   = note: required because of the requirements on the impl of `std::convert::Into<geo_types::polygon::Polygon<_>>` for `shapefile::record::polygon::GenericPolygon<T>`
   = note: required because of the requirements on the impl of `std::convert::From<shapefile::record::polygon::GenericPolygon<T>>` for `geo_types::multi_polygon::MultiPolygon<_>`
   = note: required by `std::convert::From::from`
```

**Comment by Farkal** [comment]
Are you sure you have the feature "geo-types" activated on the lib ?

**Comment by rfilmyer** [comment]
I believe so. More context: 

In my `cargo.toml` file I have the following listed as dependencies:
```
[dependencies]
geo = "^0.14.1"
geo-types = "^0.6.0"
shapefile = { version = "^0.2.0", features = ["geo-types"] }
```

which I believe enables the `geo-types` feature for `shapefile`. I run into this whether I am passing a ``shapefile::Polygon`, a `shapefile::shapes::Polygon`, or a `shapefile::record::polygon::Polygon`. My entire function is as follows:

```
fn district_contains_point<T>(district: &(Polygon, T), point: geo::Point<f64>) -> bool {
    let (shape, _) = district;
    let shape = geo_types::MultiPolygon::from(shape); // E0277

    shape.contains(&point)
}
```

**Comment by Farkal** [comment]
If you use `into` function it doesn't work ?
`let shape = geo_types::MultiPolygon::from(shape.into());`

**Comment by tmontaigu** [comment]
I think you have to explicitly ask for a Multipolygon<f64>

`ˋ`rust
let multipoly: geo_types::MultiPolygon<f64> = shape.into()

`ˋ`

**Comment by rfilmyer** [comment]
So for the first - `let shape: geo_types::MultiPolygon<f64> =  shape.into();` - I get:

```
error[E0277]: the trait bound `geo_types::polygon::Polygon<f64>: std::convert::From<shapefile::record::polygon::GenericPolygon<shapefile::record::point::Point>>` is not satisfied
  --> src/main.rs:47:54
   |
47 |     let shape: geo_types::MultiPolygon<f64> =  shape.into();
   |                                                      ^^^^ the trait `std::convert::From<shapefile::record::polygon::GenericPolygon<shapefile::record::point::Point>>` is not implemented for `geo_types::polygon::Polygon<f64>`
   |
   = help: the following implementations were found:
             <geo_types::polygon::Polygon<T> as std::convert::From<geo_types::rect::Rect<T>>>
             <geo_types::polygon::Polygon<T> as std::convert::From<geo_types::triangle::Triangle<T>>>
   = note: required because of the requirements on the impl of `std::convert::Into<geo_types::polygon::Polygon<f64>>` for `shapefile::record::polygon::GenericPolygon<shapefile::record::point::Point>`
   = note: required because of the requirements on the impl of `std::convert::From<shapefile::record::polygon::GenericPolygon<shapefile::record::point::Point>>` for `geo_types::multi_polygon::MultiPolygon<f64>`
   = note: required because of the requirements on the impl of `std::convert::Into<geo_types::multi_polygon::MultiPolygon<f64>>` for `shapefile::record::polygon::GenericPolygon<shapefile::record::point::Point>`
```

And for the second - `let shape = geo_types::MultiPolygon::<f64>::from(shape);` - I get:

```
error[E0277]: the trait bound `geo_types::polygon::Polygon<f64>: std::convert::From<shapefile::record::polygon::GenericPolygon<shapefile::record::point::Point>>` is not satisfied
  --> src/main.rs:46:17
   |
46 |     let shape = geo_types::MultiPolygon::<f64>::from(shape);
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<shapefile::record::polygon::GenericPolygon<shapefile::record::point::Point>>` is not implemented for `geo_types::polygon::Polygon<f64>`
   |
   = help: the following implementations were found:
             <geo_types::polygon::Polygon<T> as std::convert::From<geo_types::rect::Rect<T>>>
             <geo_types::polygon::Polygon<T> as std::convert::From<geo_types::triangle::Triangle<T>>>
   = note: required because of the requirements on the impl of `std::convert::Into<geo_types::polygon::Polygon<f64>>` for `shapefile::record::polygon::GenericPolygon<shapefile::record::point::Point>`
   = note: required because of the requirements on the impl of `std::convert::From<shapefile::record::polygon::GenericPolygon<shapefile::record::point::Point>>` for `geo_types::multi_polygon::MultiPolygon<f64>`
   = note: required by `std::convert::From::from`
```

Is it possible that the points themselves are not able to be converted? Because I noticed when I tried to see if I could convert points back and forth, I get similar errors.

```
    let lat = 42.3894119;
    let lon = -71.1218877;

    let geo_point = geo::point!(x: lon, y: lat);

    let converted_geo_point = shapefile::Point::from(geo_point.clone()); // <- the trait bound `shapefile::record::point::Point: std::convert::From<geo_types::point::Point<{float}>>` is not satisfied

    let shapefile_point = shapefile::Point::new(lat, lon);

    let converted_shapefile_point = geo::Point::from(shapefile_point); // <-  the trait bound `geo_types::point::Point<_>: std::convert::From<shapefile::record::point::Point>` is not satisfied
```

I'm still not sure how to fix, but I'd be more than happy to help out with a PR if it just turns out we need to add some more implementations.

**Comment by tmontaigu** [comment]
You should be able to convert between `geo_types::Point` & `shapefile::Point`  the implementations are there https://github.com/tmontaigu/shapefile-rs/blob/251a59b18e2880ca362d05dd0081b591db1427fb/src/record/point.rs#L95

It stills looks like cargo does not compile shapefile-rs with the geo-types feature activated otherwise the point conversions would be found.

And the fact that when you try to convert into a `Multipolygon<f64>` the error is about :    `std::convert::From<shapefile::Polygon> is not implemented for geo_types::polygon::Polygon<f64>` , makes me think that rustc does not find our implementation of `std::From<shapefile::Polygon> for geo_types::MultiPolygon<f64>` that is here https://github.com/tmontaigu/shapefile-rs/blob/251a59b18e2880ca362d05dd0081b591db1427fb/src/record/polygon.rs#L521 

And instead tries to use the  [another std::from implementation](https://docs.rs/geo-types/0.6.0/geo_types/struct.MultiPolygon.html#impl-From%3CIP%3E)


What happens if in your `cargo.toml` you  use `geo_types = "^=0.4.3"` (same version as shapefile-rs)

**Comment by rfilmyer** [comment]
Sure enough, my code compiles and works as expected.

**Comment by rfilmyer** [comment]
That's interesting behavior that I wasn't aware of (I'm somewhat new to Rust), but fortunately it's more straightforward to sanity check. Would it be worth it for me to test this crate against more recent versions of `geo-types`, and if compatibility is maintained I can submit a PR to broaden the dependency? I can bring this up in a separate issue.

**Comment by tmontaigu** [comment]
Yes, we have to find what to do so that the experience is smoother
