### ISSUE TITLE
Publish new release with geo-types updates

### ISSUE THREAD

**Issue by pjsier** [tmontaigu/shapefile-rs#17]
The changes for allowing multiple versions of `geo-types` look great, thanks for maintaining this! Would it be possible to publish a new release with those updates?

**Comment by rfilmyer** [comment]
(this could probably be a v0.2.1, and then whenever appropriate a v0.3 could remove support for earlier versions)

**Comment by tmontaigu** [comment]
I though I already did a release with the changes, it appears that it was not the case so I pushed version 0.2.1

**Comment by pjsier** [comment]
Great, thanks for the quick response!
