### ISSUE TITLE
Not able to read feature metadata.

### ISSUE THREAD

**Issue by xinaesthete** [tmontaigu/shapefile-rs#19]
I'm very new to Rust (somewhat experienced with GIS but it's not my main background), so apologies if there's something I just failed to grok properly.

I'm trying to read shapefiles with contour lines (from the Ordanance Survey Terr50 data FWIW), which are grouped into features with 2d coordinates and a `'PROP_VALUE'` indicating the height of each line.  I've previously been using https://github.com/calvinmetcalf/shapefile-js and wanted to experiment with porting [that code](https://github.com/xinaesthete/psychogeo/blob/main/public/shp-worker.js) to Rust / WASM.

In the context of `shapefile.js`, they parse the results into GeoJSON `FeatureCollection`, where each `Feature` has, in addition to geometry, a set of arbitrary properties indexed by string. So I access the height with `feature.properties['PROP_VALUE']`.

Reading through your documentation and code, I don't think I see anyway to do the equivalent with shapefile-rs, so I guess it's just a missing feature, but I could well have missed something.

**Comment by xinaesthete** [comment]
I see that you do have `dbase::Record` read from `dbf`, I think I'm on the right track now (a bit spoiled by `shapefile.js` being able to parse a zip directly, combining these elements appropriately).

**Comment by tmontaigu** [comment]
Hello,

In shapefile-rs, to access the properties associated to a geometry you first have to use [Reader::iter_shapes_and_records](https://docs.rs/shapefile/0.2.1/shapefile/reader/struct.Reader.html#method.iter_shapes_and_records) to get an iterator that gives you both the `shape` (aka the geometry) and the `record` (aka the properties). 

The record will be a [hashmap that maps String to Values](https://docs.rs/dbase/0.0.4/dbase/type.Record.html) that yoy can use to get the values you want

**Comment by xinaesthete** [comment]
For now as a Rust-learning-exercise I'm fairly impressed by how easily opening a zip archive and processing the contents through your library is going with just a couple of extra lines of code, but it seems like it'd make sense for you to incorporate in a more comprehensive way to the library if you have time.
